site_name: Roar User Guide
site_url: https://icds-docs.readthedocs.io/en/latest

theme: 
  name: readthedocs
  highlightjs: false
  logo: img/PSU_ICDS_logo_blue.png
  site_favicon: img/favicon.ico
  next_previous: true

extra_css: 
    - css/extra.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences

plugins:
    - bootstrap4-blockquotes
    - bootstrap4-tables

nav:
    - Getting Started: 01_GettingStarted
    - Handling Data: 10_HandlingData
